### ISSUE TITLE
Promise function error

### ISSUE THREAD

**Issue by navinnarkhede** [algolia/firestore-algolia-search#100]
![20220318_232121.jpg](https://user-images.githubusercontent.com/95497694/159103024-54fb0651-a03e-4ae8-bac3-d28139288c7c.jpg)
Console:-
Stripe payement is not working 
![IMG-20220318-WA0003.jpeg](https://user-images.githubusercontent.com/95497694/159103028-a37f2fe9-3457-4e74-a61b-bcc8ae80bb86.jpeg)

**Comment by smomin** [comment]
I think you are trying to run the integration outside of the Firebase service.  If you can let me know what you are attempting to do, then I can properly direct you.

**Comment by navinnarkhede** [comment]
> I think you are trying to run the integration outside of the Firebase service.  If you can let me know what you are attempting to do, then I can properly direct you.

What can we do now ?

**Comment by smomin** [comment]
Closing this issue for now.
