### ISSUE TITLE
Migration of large dataset returns Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old

### ISSUE THREAD

**Issue by rayanoncyber** [algolia/firestore-algolia-search#101]
Hey! 

We're trying to migrate our firestore data to Algolia (~5 million records) and we keep facing this issue. Seems like it's related to firestore failing to fetch that much data. Any known or upcoming fix to batch fetch? 

Thanks a lot!

**Comment by Haroenv** [comment]
Hi @rayanoncyber, where are you getting this error? Do you have a stack trace or similar? I don't recognise this error from this code, so I wonder if it's maybe in Firebase itself?

**Comment by rayanoncyber** [comment]
This is what I get about 5 minutes after running the command

<img width="727" alt="Screen Shot 2022-03-23 at 11 13 43 AM" src="https://user-images.githubusercontent.com/56723055/159675973-0c9a5b9c-25e9-4211-99ce-893a74837d7c.png">

**Comment by Haroenv** [comment]
Not too sure what can cause this, but it is implied the individual connection is too "old", and it should be processed in batches (eg. https://stackoverflow.com/questions/64712587/google-cloud-pub-sub-function-gives-the-requested-snapshot-version-is-too-old, https://github.com/firebase/functions-samples/issues/890, https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/firestore/src/remote/rpc_error.ts#L76)

**Comment by rayanoncyber** [comment]
The error came from the firestore-algolia-search module trying to fetch all documents at once (with big datasets it fails). 

I re-wrote retrieveDataFromFirestore to take care of it in sequences through a recursive function. Hope it can help some people with the same problem

`const retrieveChunk = async (lastVisible, maxLength) => {
    const collectionPathParts = config_1.default.collectionPath.split('/');
    const collectionPath = collectionPathParts[collectionPathParts.length - 1];
    let querySnapshot;

    if (lastVisible) {
        querySnapshot = await database.collection(collectionPath).orderBy('number_of_visits').limit(maxLength).startAfter(lastVisible).get();
    }
    else {
        querySnapshot = await database.collection(collectionPath).orderBy('number_of_visits').limit(maxLength).get();
    }

    processQuery(querySnapshot).catch(console.error);
    
    return [querySnapshot.docs[querySnapshot.docs.length - 1], querySnapshot.docs.length];
};

const retrieveDataFromFirestore = async (lastVisible=null) => {
    const maxLength = 100;
    const [keepGoing, length] = await retrieveChunk(lastVisible, maxLength);
    console.log("LENGTH", length);
    if (length == maxLength) retrieveDataFromFirestore(keepGoing);
};
`

**Comment by Haroenv** [comment]
This is very useful, thanks! If you are confident in this code, feel free to make a pull request :)

**Comment by smomin** [comment]
@rayanoncyber did you want to send a PR?

**Comment by adamunchained** [comment]
> @rayanoncyber did you want to send a PR?

It would have been more practical to implement it instead of closing as it makes migration tool useless for bigger datasets.

**Comment by aagarcia** [comment]
someone was make this change for support large collections.

**Comment by ddimitrioglo** [comment]
> if (lastVisible) {
>     querySnapshot = await database.collection(collectionPath).limit(maxLength).startAfter(lastVisible).get();
> } else {
>     querySnapshot = await database.collection(collectionPath).limit(maxLength).get();
> }

Curious if this approach (using `.get()`) can guarantee the correct order of execution... Usually, chunks go together with sorting.
