### ISSUE TITLE
Merge multiple Firestore collections into one Algolia index

### ISSUE THREAD

**Issue by aliechti** [algolia/firestore-algolia-search#103]
In Firestore we have the limitation that we cannot do read restrictions so we have multiple collections for users.
https://firebase.google.com/docs/firestore/security/rules-fields#allowing_read_access_only_for_specific_fields

But in Algolia we need both collections for our search query.

So do we have to do this manually or is it possible to do this with this plugin?
If not how should we approach such a scenario?

**Comment by Haroenv** [comment]
In Algolia you have two options, the first is the same as for firebase, different indices or filters for different privacy levels. The second is to add the "private" information in specific attributes, and then add it to [`unretrievableAttributes`](https://www.algolia.com/doc/api-reference/api-parameters/unretrievableAttributes/) via a [secured api key](https://www.algolia.com/doc/guides/security/api-keys/#main-and-virtual-secured-api-keys)

**Comment by thejahweh** [comment]
@Haroenv Thanks for your reply, but that wasn't my question. We don't plan to allow access to our Algolia index publicly, so privacy isn't a problem.

What we want is one merged index in Algolia with both Firebase collections in it.

**Comment by Haroenv** [comment]
Sorry, I missed the part of the issue where you decided it should be in a single index. With the design of this plugin, that would not be possible, as it's meant for a single firebase collection taking ownership of an index. What you could do is fork and in extract https://github.com/algolia/firestore-algolia-search/blob/main/functions/src/extract.ts point multiple collections to the same index

**Comment by thejahweh** [comment]
Ok I've looked into the code, what we could do is just remove the part in which it checks if there is something to remove:
https://github.com/algolia/firestore-algolia-search/blob/1b9421bd1036a982578a3b5efe12f258c1557126/functions/src/index.ts#L71

Then we could use it for both collections (add the extension twice). The downside is that if we would remove fields in one Firebase collection they would still exist in the Algolia index.

**Comment by Haroenv** [comment]
That would indeed make sense. Alternatively you could add a unique attribute to each "subindex" via transformer, and only remove those that match that attribute

**Comment by smomin** [comment]
hey @aliechti, I am looking to address this in a more elegant manner.  can you send me the json structure that you want to see in Algolia.

**Comment by aliechti** [comment]
> hey @aliechti, I am looking to address this in a more elegant manner. can you send me the json structure that you want to see in Algolia.

I can send you our solution too if you want, of course it got a bit more specific to our case, but maybe it helps.

What we have now is a structure like this:
```yaml
profiles:
  uidxyz:
    name: 'Example'
users:
  uidxyz:
    email: 'e@xam.ple'
    position: [47.3778579,8.5381339]
accounts:
  uidxyz:
    lastActiveDate: timestamp
```
So in Algolia we group it too to not overwrite other records from other collections. Then we move the `position` to the root as `_geoloc`. A `lastmodified` entry is added to the root too. There are still some improvements we could make, but for now it works like a charm.
```yaml
objectID: 'uidxyz'
profile:
  name: 'Example'
user:
  email: 'e@xam.ple'
account:
  lastActiveDate: timestamp
_geoloc: {lat: '47.3778579', lng: '8.5381339'}
```

**Comment by smomin** [comment]
thank @aliechti for the information.

**Comment by RandomToni** [comment]
This is a really good question. @Haroenv do you have any suggestions on what aliechti asks?
It's crazy that with the versatility of algoria, something like getting the data from 2 or more different collections can be a challenge to achieve.
@aliechti were you able to find a solution?

**Comment by smomin** [comment]
@RandomToni 

This is not an Algolia issue but a Firebase Extension Framework Architecture limit.  What @aliechti is asking is not achievable in the extension alone.  You will need to create a transformation function to look up the parent property and parent Id.  using this information, you can construct a payload to send to Algolia.

**Comment by RandomToni** [comment]
@smomin thank you for your answer. Is there any way we can get support for getting the extension upgraded?

**Comment by smomin** [comment]
Is your use case identical to the one that is defined in the ticket? To implement the use case identified in the ticket, it’s a large effort and it’s .  The extension is community supported so if you have an approach, please create a PR and I will review it.Sent from my iPhoneOn Oct 6, 2023, at 4:15 AM, RandomToni ***@***.***> wrote:﻿
@smomin thank you for your answer. Is there any way we can get support for getting the extension upgraded?
