### ISSUE TITLE
Can't sync index of subcollection.

### ISSUE THREAD

**Issue by Suyama-Daichi** [algolia/firestore-algolia-search#104]
Hello. thank to this solution.

In this time, I found that can't sync index of subcollection in version 0.5.9.

Reproduction.

Pattern A.
- Create a collection in root.
→ This extention was created the index and the object in Algolia.

Pattern B.
- Create a subcollection in specific document.
→ It was'nt.

As far as I know, It was working also Pattern B in past.

Would,nt works with sub collection now ?

Help me.

**Comment by smomin** [comment]
How many Algolia Extensions installed?
Can you provide me configuration details for all the Algolia extension installation?

**Comment by smomin** [comment]
What is the configuration on the Algolia Extension monitoring the subcollection?

**Comment by Suyama-Daichi** [comment]
@smomin 
The settings is bellow.

`list_item_ids` is subcollection.
I retried but not work now too.
![image](https://user-images.githubusercontent.com/35884504/163108241-ae5bf98f-93b8-4dcb-b673-e29ef4d22d62.png)

**Comment by smomin** [comment]
Well, `Collection Path` should be set to this pattern `parent_collection/{parentId}/target_collection`.  What is your parent collection that has `list_item_ids`?

**Comment by Suyama-Daichi** [comment]
Oops!

I resolveed it!
The configuration was bellow.

![image](https://user-images.githubusercontent.com/35884504/163527315-e0d2e642-d3ae-4335-a552-da43d1274433.png)

Thank you.
