### ISSUE TITLE
Transform functions with Algolia firestore extenstion

### ISSUE THREAD

**Issue by dejiemiabata** [algolia/firestore-algolia-search#105]
I am trying to utilise the transform functions option within Algolia. I have tried the following to no avail and I keep getting errors such as “unexpected token < in json”.

Basically, my posts collection has a userId field which I am trying to transform before sending to algolia. The transformed function should grab the userId field and output data from the users collection.

Below you can see the transform function I am testing out + errors.

I tried using the reference here: https://github.com/algolia/firestore-algolia-search. Is there a better example for how to use transformFunctions in algolia ?

`{"severity":"ERROR","message":"Error when performing Algolia index FetchError: invalid json response body at https://accounts.google.com/ServiceLogin?passive=true&continue=https://uc.appengine.google.com/_ah/conflogin%3Fstate%3D~AJKiYcFxxGMUMqCfFkvubLonYRaXN50w_Kw_5BO6hlCr9LlWPxIaPm01U1D5BFEJR2W5JR-Q8ongrJkEq0TKW5n2ihpQV2fsjUTIDVdnrzDWqXPPEx6C20M3Z_QT4XokgmlYmS-QMqceAyKYJuVu3YrbfKddijM1rIc-rvF8z8WPfBqr4zjFjlu1tPjDHrsyl58Ic8grr-onj-vSrdsfM3id89TcPaADCP18cFoHU1zKHz6Kk3SY2SrUhsAi6gNM6OQrkgwtT83R reason: Unexpected token < in JSON at position 1\n    at /Users/xxxxx/.npm/_npx/0ca4ecfa9810ae5b/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.exports.default (/Users/ddddd/.npm/_npx/0ca4ecfa9810ae5b/node_modules/firestore-algolia-search/lib/transform.js:29:26)\n    at async Object.extract [as default] (/Users/xxxx/.npm/_npx/0ca4ecfa9810ae5b/node_modules/firestore-algolia-search/lib/extract.js:42:21)\n    at async processQuery (/Users/xxx/.npm/_npx/0ca4ecfa9810ae5b/node_modules/firestore-algolia-search/lib/import/index.js:54:29) {\n  type: 'invalid-json'\n}"}`

```
export const transformPosts = functions.region("us-central1").https.onCall(async (payload) => {
  const { userId: userIds } = payload
  const userId = await localFirestore.collection("users").doc(userIds).get()
  return { userId }
})
```

**Comment by i14h** [comment]
it seems that the post request is being redirected to a Google login page which returns html but the request is expecting json

**Comment by dejiemiabata** [comment]
@i14h okay do you know the right approach to creating a transform function that will work with algolia search ?

**Comment by smomin** [comment]
@dejiemiabata Try creating a function that allows unauthenticated invocations.

<img width="625" alt="Screen Shot 2022-04-13 at 9 33 23 PM" src="https://user-images.githubusercontent.com/1305323/163314314-a41dfb07-274a-4979-8b24-6920adf2418c.png">

**Comment by dejiemiabata** [comment]
@smomin I have allowed unauthenticated invocations but the error still persists.

**Comment by dejiemiabata** [comment]
<img width="1375" alt="Screenshot 2022-04-15 at 07 41 59" src="https://user-images.githubusercontent.com/77588661/163566817-4ab49915-e2be-4b02-a92c-b3260b01ff54.png">

@smomin still not working

**Comment by smomin** [comment]
I am looking into it.  I will let you know my findings.

**Comment by dejiemiabata** [comment]
@smomin I noticed I had the PROJECT_ID was pointing to the wrong project. Sorry for the confusion here.
