### ISSUE TITLE
Transforming objectID creates problems on deletion

### ISSUE THREAD

**Issue by drewzb** [algolia/firestore-algolia-search#114]
I have a transform function which modifies the objectID. 

```
const algoliaUserTransform = (payload) => {
  const array = payload.path.split('/')
  const userID = array[1]
  return {
    ...payload,
    objectID: userID + '|' + payload.objectID,
    user_id: userID,
  }
}
```

I do this because sometimes I duplicate an entire user in Firestore -> which results in objectID collisions. This worked great until I noticed that documents deleted from Firestore are not being run through the transform function -> thus the document is not being deleted from Algolia.

For example:
objectID: 123
userId: abc

My transform function gives a new objectID of: abc|123
In Algolia, the objectID is: abc|123  <- perfect!

Now when I delete the document in Firestore, the firestore-algolia-search only looks for "123" to delete, which it does not find. So "abc|123" does not get deleted!

**Comment by smomin** [comment]
Is there a reason why the original objectId is being manipulated?

**Comment by smomin** [comment]
hey @drewzb the objectId was not meant to be manipulated.  Since there is a additional cost when using Transformation Functions, I will need to add a configuration on the delete action to call the transformation function if defined.  Let me get back to you.

**Comment by drewzb** [comment]
Thanks, I found a workaround for my needs. So this isn't needed by me
anymore. Maybe for future users, add to the docs that the objectId was not
meant to be manipulated. That way they don't find out after the fact that
things weren't deleted.

**Comment by smomin** [comment]
I will make sure to do that.

**Comment by jodovaljow** [comment]
same problem here

**Comment by jodovaljow** [comment]
I want to use firestore path as objectId
