### ISSUE TITLE
How to use same fields, collections but multiple environments index name?

### ISSUE THREAD

**Issue by SohelIslamImran** [algolia/firestore-algolia-search#115]
How to use one extension instance with multiple environments [index name](https://github.com/algolia/firestore-algolia-search#:~:text=Algolia%20Index%20Name%3A%20What%20is%20the%20Algolia%20index%20name%3F%20This%20is%20the%20name%20of%20the%20Algolia%20index%20where%20the%20records%20will%20be%20persisted.%20Refer%20to%20naming%20your%20index%20for%20more%20information.) `dev_NAME`, `test_NAME`, or `prod_NAME`?

 I have an index with multiple environments index name, eg. `dev_products`, `test_products` and `prod_products`. All these are subscribing to single firestore collection name `products`. So is there any way to use single extension instance for these multiple environments index name
 
![image](https://user-images.githubusercontent.com/76745339/176306929-9270c7fd-3a26-44a7-89be-d081256c4ab0.png)

**Comment by smomin** [comment]
Currently the extension is not set up to send data to multiple indices.  You will have to install the extension multiple times for now to send to different Algolia Indices.

**Comment by smomin** [comment]
It looks like the issue is resolve.  Please reopen if needed.
