### ISSUE TITLE
Error when setting up extension

### ISSUE THREAD

**Issue by Nethrenial** [algolia/firestore-algolia-search#118]
I've tried to install this extension, but it errors out with a rather cryptic error, and multiple google search didn't lead me to any answers.
This is the error I'm getting,

Use the details below to help resolve this error, then retry installing the extension. If you continue to get this error, we recommend uninstalling the extension to remove any extension resources that might be deployed.

; ERROR_PROCESSING_REQUEST at : Unreachable URL https://cloudfunctions.googleapis.com/v1/projects/aiesec-opportunities/locations/asia-south1/functions, reason: UNREACHABLE_5xx, code: 500

At first, I thought the cloud function was not getting created for some reason, but the google cloud dashboard shows that a function with this region is created and exists.
Can anyone help me figure out why this is happening

**Comment by smomin** [comment]
This might be a firebase provisioning issue.  Can you provide all your configuration information and logs?

**Comment by smomin** [comment]
closing due to no response.
