### ISSUE TITLE
Algolia index not updating NULL fields

### ISSUE THREAD

**Issue by aceligowska** [algolia/firestore-algolia-search#121]
Hello

I encountered very similar case to issue mentioned here: https://github.com/algolia/firestore-algolia-search/issues/60
But unlike there, I did not delete key. I updated it to NULL instead:

fieldName: { ... some map ... }
To:
fieldName: null

I cannot delete key, because I need to support filters with NULL condition.
Setting keys to null does not update algolia index, unfortunately.

I looked at relevant PR, it seems checking for undefined keys:

```
const undefinedAttrs = Object.keys(beforeData).filter(key => after.get(key) === undefined);

// if no attributes were removed, then use partial update of the record.
if (undefinedAttrs.length === 0) {
```

I am no expert in javascript code, but I guess it should be more something like this:

```
const undefinedAttrs = Object.keys(beforeData).filter(key => after.get(key) === undefined);
const nullAttrs = Object.keys(beforeData).filter(key => after.get(key) == null);

// if no attributes were removed, then use partial update of the record.
if (undefinedAttrs.length === 0 || nullAttrs.length == 0) {
```

Then, perhaps setting keys to null would also update algolia.
Would it be possible to fix this? thanks

**Comment by smomin** [comment]
i am working on the deployment process using the new firebase CLI.  once i have this working, I will look into this issue.  there is probably a reason why I did not add it.

**Comment by aceligowska** [comment]
Hello, any update on this?

**Comment by smomin** [comment]
yes, i am waiting for a review from my colleagues.
