### ISSUE TITLE
Erro update extesion algolia into firebase

### ISSUE THREAD

**Issue by linikerunk** [algolia/firestore-algolia-search#125]
Reconfigure extension in Firebase has been a problem...
As the image show:

![image](https://user-images.githubusercontent.com/27506588/189439069-41f5212d-681f-4bdb-a8fa-90fcf724b1d5.png)

**Comment by linikerunk** [comment]
![image](https://user-images.githubusercontent.com/27506588/189439439-7f7113eb-c9df-4588-94bc-182b6de023ff.png)

**Comment by linikerunk** [comment]
![image](https://user-images.githubusercontent.com/27506588/189439471-6f38bd6e-dd92-4d46-92ed-f63193b0ddb7.png)

**Comment by linikerunk** [comment]
![Sem título](https://user-images.githubusercontent.com/27506588/189441128-4a298010-00b7-4977-b834-01333147a78e.png)

**Comment by smomin** [comment]
This might be a firebase or Google cloud issue.  Please open a ticket with Firebase team.
