### ISSUE TITLE
Lib files are included in the repository

### ISSUE THREAD

**Issue by dackers86** [algolia/firestore-algolia-search#126]
Firebase Extensions builds the source files during installation and therefore do not require to be committed.

The existing `prepare` script will generate these files.

Steps, required:

- [ ] Add lib to .gitignore
- [ ] Remove currently committed files from the repository.
- [ ] setup CI to run tests & linting
- [ ] fix all formatting issues
- [ ] fix out of date package locks
- [ ] fix all lint issues

**Comment by smomin** [comment]
I am working on this task.  I hope to get this updated soon.
