### ISSUE TITLE
Feature request: REMOVE commandline inputs for import process

### ISSUE THREAD

**Issue by benomatis** [algolia/firestore-algolia-search#129]
I really don't like the new way of having to input every piece of info in an input style format during import, a feature, apparently, introduced in v0.5.13. Can you, at least, make it optional? In the previous way I could simply copy and paste it from the extension, and it was done in one go, now I have to individually copy and paste every value - very time consuming and annoying.

**Comment by smomin** [comment]
I will look into allowing this but this is not a high priority at this time if you have a PR, please submit it.

**Comment by smomin** [comment]
With the new integration, v1.1.0, the import CLI command is removed.

**Comment by benomatis** [comment]
For anyone else looking for the reason:

https://github.com/algolia/firestore-algolia-search/blob/993481717d7931c7f5f7073044e821923a460e1e/POSTINSTALL.md?plain=1#L11-L15
