### ISSUE TITLE
Manually trigger plugin

### ISSUE THREAD

**Issue by Davste93** [algolia/firestore-algolia-search#131]
Hello!

I saw there is quite a significant delay between the document being updated on firebase and that change being reflected on Algolia in a search result.

Is there any way to force this plugin to trigger manually to expedite the change, or is the only way around it to manually update those entities in Algolia through the REST API?

Thank you so much!

**Comment by smomin** [comment]
I am not sure I understand what you mean by "manually trigger".  By changing the document, Firestore will trigger the Algolia indexing process.

**Comment by smomin** [comment]
Are there any more insight on what you are looking for here.  If not, I will close this issue.
