### ISSUE TITLE
[help request] Transform Function auth error

### ISSUE THREAD

**Issue by foush** [algolia/firestore-algolia-search#132]
I'm successfully using the Algolia extension to sync a few Firestore collections into my Algolia project. There is one collection I would like to apply a transform function to

I've followed the docs in setting up the cloud function

```
export const transformFoo = functions.https.onCall((data, context) => {...}
```

which I've deployed and then specified in the extension config. I'm observing an error in the extension logs where the transform function doesn't appear to be accessible:

```
Error when performing Algolia index { FetchError: invalid json response body at https://accounts.google.com/v3/signin/identifier?...

reason: Unexpected token < in JSON at position 0 at /workspace/node_modules/node-fetch/lib/index.js:273:32 at process._tickCallback (internal/process/next_tick.js:68:7) message: 'invalid json response body at https://accounts.google.com/v3/signin/identifier?...
```

Does this mean the Algolia extension is attempting an auth flow to call the transform cloud function? It's unclear to me what permission/role I need to grant the extension's service account. Did I miss a configuration step? I'm at a bit of a loss so any help would be appreciated.

**Comment by foush** [comment]
I realized my functions were not deployed in the same region as the extension. Creating a new extension in the same region as the transform function resolved the issue.

**Comment by jim-alexander** [comment]
My function, database and extension are all in the same location `australia-southeast1` and i'm having the same issue.

**Comment by derFunk** [comment]
I'm having the same issue, is there any update on how the permissions on the transform cloud function should be set up?

I tried giving ext-firestore-algolia-search@{project}.iam.gserviceaccount.com "Cloud Functions Invoker" permissions, but that did not help.

Only giving "Cloud Functions Invoker" role to "allUsers" on my transform cloud function worked eventually, but that's pretty insecure.

https://github.com/algolia/firestore-algolia-search/blob/a62ccdaa6251a0cfffdfa40d3cd782b450f9e752/functions/src/transform.ts also does not show any signs of other auth methods used.
