### ISSUE TITLE
Add ability to choose all subcollections

### ISSUE THREAD

**Issue by VolodymyrReient** [algolia/firestore-algolia-search#133]
I have a collection "announcements". This collection has a six subcollections. An example of collection -  [screen](https://i.stack.imgur.com/1fop6.png). I can index only one subcollection (e.x path - `announcements/announcements/list`)

I think it's good to be able to choose all subcollections  into a single search index:
e.x  `announcements/*/list`  ( symbol `*` just for example)
When i set collection path like  `announcements/*/list` algolia index all subcollections

Probably this link will be usefull [link](https://stackoverflow.com/questions/74194391/how-to-configure-the-right-collection-path-for-algolia/)

**Comment by smomin** [comment]
Based on your suggestion, this doesn't know seem to be under our control.  The Firebase team allows for one collection at a time to be monitored per extension.  You can install the extension multiple times to listen for each sub collection.   You might want to chat with the Firebase team on this use case to see what they say.

**Comment by VolodymyrReient** [comment]
> Based on your suggestion, this doesn't know seem to be under our control. The Firebase team allows for one collection at a time to be monitored per extension. You can install the extension multiple times to listen for each sub collection. You might want to chat with the Firebase team on this use case to see what they say.

Maybe add ability to configure more that one Collection Path at the same time (e.x create second input for Collection Path) - [this field](https://i.stack.imgur.com/X37ty.png)

**Comment by smomin** [comment]
hey @VolodymyrReient adding additional inputs would not really do anything if the provision scripts are not set up to recognize the additional inputs.  The provisioning scripts are managed by the Firebase team.
