### ISSUE TITLE
not syncing on new records?

### ISSUE THREAD

**Issue by jonathan-chin** [algolia/firestore-algolia-search#134]
I installed the algolia extension 1-2 months ago and followed the instructions to do the initial data import.

however, subsequent changes do firestore have not triggered updates on algolia. currently, I have a new record in one of my collections (verified on Firebase dashboard) but searching for its id in algolia returns no results.

**Comment by smomin** [comment]
hey @jonathan-chin sorry for the delay, has the issue been resolved?  can you share your configuration details?

**Comment by smomin** [comment]
I am closing this issue, but please reopen if you can share additional details.
