### ISSUE TITLE
Better descriptions for params in extension config

### ISSUE THREAD

**Issue by i14h** [algolia/firestore-algolia-search#14]
Descriptions for some params are too short and assume the user knows the details about Algolia which might not be the case. A better more descriptive message would help. A link to the related docs would  also help (for all params) 

![image](https://user-images.githubusercontent.com/678917/114639631-32b05d80-9c83-11eb-8e12-09d7d0122000.png)

**Comment by jhuleatt** [comment]
Example from Stripe extension: https://github.com/stripe/stripe-firebase-extensions/blob/abb30f929a5538139034302bc229018f2c1555b3/firestore-stripe-subscriptions/extension.yaml#L200-L203

**Comment by smomin** [comment]
#20
