### ISSUE TITLE
Path overwriting firestore field

### ISSUE THREAD

**Issue by Mawizzler** [algolia/firestore-algolia-search#140]
Is it possible to opt out of the creation of the path field because my collection contains a field called path and currently gets overwritten by the script with the firestore document path?

**Comment by Mawizzler** [comment]
My document has a field called 'path' and I can't even use a transform function to change it before sending it to algolia because it gets overwritten with the collection path by the extension. Any ideas on how I could fix this?

![CleanShot 2022-11-08 at 10 42 37@2x](https://user-images.githubusercontent.com/17184591/200530785-a8a763f5-5cd7-45bc-9830-1c903080f426.png)

<img width="572" alt="CleanShot 2022-11-08 at 10 44 32@2x" src="https://user-images.githubusercontent.com/17184591/200531091-8e4195fa-1f2f-4161-9790-ad8c5eba191f.png">

**Comment by smomin** [comment]
Based on the code, you should be able to change the path field in the Transform function.  The entire payload is sent to the Transform function and the result is what gets used in Algolia.  Can you provide details on the Transform function?
