### ISSUE TITLE
Aloglia API key

### ISSUE THREAD

**Issue by mulsubaie** [algolia/firestore-algolia-search#146]
when I try to add Aloglia API key into my Firebase Algloia extension it show's me an error that says add secret key first, what does it mean?
![image_2023-02-03_20-14-16](https://user-images.githubusercontent.com/94124100/216676581-78cd529e-c43c-4114-acfd-40ac43dfa7bb.png)

**Comment by mulsubaie** [comment]
@smomin @mbleigh Can you guys help?

**Comment by smomin** [comment]
Is there error shown when you click on "Create secret"?  I will try to install a fresh extension to see if I encounter the same issue.  In mean time, you should open a ticket with Firebase team on the secret error as well.

**Comment by smomin** [comment]
Also, during installation, did you enable the secrets manager?

#
<img width="670" alt="Screenshot 2023-02-03 at 10 34 39 AM" src="https://user-images.githubusercontent.com/1305323/216681877-fca3e323-be41-4fce-bfa7-d1c3a580b11a.png">

**Comment by mulsubaie** [comment]
It shows the same error when I click create secrete, and yes I've enabled it I don't know what's wrong

**Comment by smomin** [comment]
Have you opened a ticket with the firebase team.  This is provided by the Firebase extension framework and not something the integration has any influence over.
