### ISSUE TITLE
Filter documents on search

### ISSUE THREAD

**Issue by arturmeinzer** [algolia/firestore-algolia-search#150]
I use the firebase extension with a collection path like this:
`users/{userId}/documents`
Indexing the data is working great!
The problem is, that I want to search only for the documents of a given user. The index includes a path field which has this pattern:
`users/{userId}/documents/{documentId}`
Is there a way to search only for data where the path starts with `users/{userId}/`?
I use the "algoliasearch" npm package, but can't find a way to restrict the search there.

**Comment by Haroenv** [comment]
By default only the fields on the firebase object are indexed, if you want the path or a part of the path also indexed, you can use the "transformer" firebase function to index more information.

**Comment by arturmeinzer** [comment]
Now I created a firebase cloud function to add the userId to the index, but I can't filter on the userId in the client. It works great in the Algolia GUI, but the following code returns 0 hits in the client:

`const client = algoliasearch(process.env.NEXT_PUBLIC_ALGOLIA_APP_ID || "", process.env.NEXT_PUBLIC_ALGOLIA_API_KEY || "");
const index = client.initIndex(process.env.NEXT_PUBLIC_ALGOLIA_INDEX || "");

export const algoliaSearch = async (userId: string, query: string) => {
    const response = await index.search(query, {
        analytics: false,
        attributesToRetrieve: ["*"],
        facets: ["*"],
        facetFilters: [`userId:${userId}}`],
        hitsPerPage: 25,
        maxValuesPerFacet: 100,
        page: 0,
        responseFields: ["*"],
    });
    console.log(response);
}`

I created a facet for userId in the GUI
