### ISSUE TITLE
add emulator support for transform function

### ISSUE THREAD

**Issue by JonasWijne** [algolia/firestore-algolia-search#159]
in https://github.com/algolia/firestore-algolia-search/blob/993481717d7931c7f5f7073044e821923a460e1e/functions/src/transform.ts#L24 you only allow external calls, but there is no way to call my local emulator suit (eg. `http://127.0.0.1:5001/transformPost` )

could you implement a way to enable this?

**Comment by smomin** [comment]
@JonasWijne if you have an approach, please create a PR for the team to review.  When I have time, I can take a look when a user in local development.

@michaeled @8bittitan Do you guys have time to look in to this?

**Comment by smomin** [comment]
Closing this issue at this time.

**Comment by blakewood84** [comment]
@smomin why isn't there support for this running locally yet?

**Comment by smomin** [comment]
At this time, transform approach is experimental but @blakewood84 if you have a PR in mind, please go ahead and submit it.
