### ISSUE TITLE
Make import script runnable via npx

### ISSUE THREAD

**Issue by i14h** [algolia/firestore-algolia-search#16]
It might be a bit of a hassle for users to clone the repo and run the import script. One option is to make it runnable via an npx command like `npx github:algolia/firestore-algolia-search/...`

**Comment by i14h** [comment]
@smomin you can take a look at the scripts for the bigquery extension https://github.com/firebase/extensions/blob/next/.github/workflows/npm_publish_bq_scripts.yml

**Comment by smomin** [comment]
This has been completed.
