### ISSUE TITLE
Problem with location

### ISSUE THREAD

**Issue by JFGHT** [algolia/firestore-algolia-search#161]
I recently installed this extension. It seems it works correct for the first task but after that, it's selecting the incorrect location (default us-central1).

My guess it's because of this line: https://github.com/algolia/firestore-algolia-search/blob/main/functions/src/index.ts#L203

Which should be:

`locations/${process.env.LOCATION}/functions/ext-firestore-algolia-search-executeFullIndexOperation`,

But I have not tested it.

PS: also when reinstalling the extension there's a problem at creating the queue with the same name because GC takes up to 7 days to remove it.

**Comment by JFGHT** [comment]
> I am working with the Firebase team on the location issue.  As for GC taking longer than 7 days, thats should be something the Firebase should help on.  I can ask but it would be good to open a ticket with them on this issue.

You could ask and we could also check how to create the queue with a dynamic name (timestamped or something).

**Comment by smomin** [comment]
@JFGHT I have created a RC https://console.firebase.google.com/project/_/extensions/install?ref=algolia/firestore-algolia-search@1.1.1-rc.0.  Use this RC version while the final build is going through the Firebase Approval process.

**Comment by JFGHT** [comment]
Thanks.

Any info regarding the 7 days restriction? Because this actually blocks me reinstalling the extension via firebase console.

And btw, could you lead me to any docs of how to install RCs or other versions of an extension?

Thanks.

**Comment by smomin** [comment]
hey @JFGHT the extension stable build is now approved so you can install this version through the extension marketplace.
