### ISSUE TITLE
Plugin started a full index even though it was configured not to

### ISSUE THREAD

**Issue by twaddington** [algolia/firestore-algolia-search#163]
<img width="212" alt="Screenshot 2023-05-29 at 4 16 16 PM" src="https://github.com/algolia/firestore-algolia-search/assets/107117/2b7a1980-0d06-444f-b64e-b5519f0916f3">

**Comment by twaddington** [comment]
Updating the field values to index also re-triggered a full index on this function.

**Comment by smomin** [comment]
Thank you for bringing this to my attention.  I have fixed the issue and submitted the updated extension to the Firebase team.

**Comment by smomin** [comment]
The v1.1.2 has been released with the fix.
