### ISSUE TITLE
multi-environment configuration broken

### ISSUE THREAD

**Issue by george43g** [algolia/firestore-algolia-search#172]
This extension works when installed for a single project.

If a user has multiple envs (staging, prod) - the `extensions/firestore-algolia-search.env` file gets overwritten. Firebase itself can cope with having multiple envs configured for a single instance of an extension, but the above file should have configuration specific to the `projectId`. Either separate files for different envs, or allow multiple env configuration within the file.

**Comment by george43g** [comment]
UPDATE: for anyone reading this - I found a solution buried within the Firebase docs: https://firebase.google.com/docs/extensions/manifest#projectspecific

You can rename the `.env.` files to allow for multi project config, but this requires overriding what the automatic extension installer does.

**Comment by smomin** [comment]
I will close this since this seems like a recommendation that is not related to the Algolia extension.
