### ISSUE TITLE
Subcollections fail the initial sync

### ISSUE THREAD

**Issue by pardis-shah** [algolia/firestore-algolia-search#175]
I have 3 extensions setup, 2 for normal collections and one for a subcollection inside one of those collections. 
1. lists
2. users
3. lists/{listID}/Items

the first 2 work as expected, they synced initially and every new record gets indexed smoothly. but the subcollection one is always failing the initial sync. I tried different syntaxes like `lists/{listID}/Items`, `lists/{id}/Items` and `lists/{list_id}/Items`. 

I saw an [issue that was reported before and got fixed in 1.1.3](https://github.com/algolia/firestore-algolia-search/issues/167), but I am using 1.1.3 and still have this issue.

here's my config:
<img width="619" alt="image" src="https://github.com/algolia/firestore-algolia-search/assets/89708492/3a6b1c9c-8107-4cd9-bda0-7cb2328e8a6a">
<img width="645" alt="Screenshot 2023-07-12 at 2 19 56 PM" src="https://github.com/algolia/firestore-algolia-search/assets/89708492/12bf4a91-9a62-4317-9cd1-1ade074dd920">

but none of them work. I always get this error in my logs, but not sure if it's related:
```
{
  "textPayload": "Function execution took 816 ms, finished with status: 'error'",
}
```

```
{
  "textPayload": "{\"name\":\"ApiError\",\"message\":\"Error: Unhandled error\\n   
 at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)\\n    
at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)\\n    
at /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:70:24\\n    
at runMicrotasks (<anonymous>)\\n    
at processTicksAndRejections (node:internal/process/task_queues:96:5)\",\"status\":400,\"transporterStackTrace\":[{\"request\":{\"data\":\"{\\\"requests\\\":[{\\\"action\\\":\\\"addObject\\\",\\\"body\\\":{\\\"listId\\\":\\\"000F0380-0C5F-44C8-86A6-EAE4BC5DF009\\\",\\\"summary\\\":\\\"samplesummary\\\",\\\"imageUrl\\\":\\\"https://secure.img1-
…
```

**Comment by smomin** [comment]
Can you try `lists/{parentId}/Items`?  Also, can you take a snapshot of the data with the Items as a collection?

**Comment by smomin** [comment]
Has this issue been resolved?

**Comment by pardis-shah** [comment]
@smomin so sorry for the late response. I did try `lists/{parentId}/Items` as well, same results.

<img width="608" alt="Screenshot 2023-07-23 at 12 42 00 AM" src="https://github.com/algolia/firestore-algolia-search/assets/89708492/880b4c6e-eeec-45d7-a73f-e2787ae6478b">

here's a sample data from the collection:
```
{
    "views": 15,
    "imageURL": "",
    "categories": [
        ""
    ],
    "visibilityLevel": "public",
    "owner": "",
    "listDescription": "",
    "id": "",
    "numberOfItems": 1,
    "likes": 0,
    "name": "",
    "items": [
        {
            "imageUrl": "",
            "listId": "",
            "id": "",
            "summary": "samplesummary",
            "views": 0,
            "author": ""
        }
    ]
}
```

**Comment by smomin** [comment]
Thanks.  I will check on this and get back to you soon as I can.

**Comment by smomin** [comment]
I have tested the extension and the full indexing works without any issues.  You might want to check the API key if you are still having problems.

**Comment by pardis-shah** [comment]
I have! I have 2 more extensions running just fine with the same API Key, the only difference is that the other ones are top level collections, and this one is a sub collection

**Comment by smomin** [comment]
Here is my current setup:
I have a collection of movies and each movie has a sub-collection of actors.  I have installed two extensions one for movies and another for actors.  With this set up, I was able to execute a full index on both collection and sub collection. 

<img width="387" alt="Screenshot 2023-08-13 at 11 05 46 PM" src="https://github.com/algolia/firestore-algolia-search/assets/1305323/7fcee235-4512-4020-9263-01b4fa4bbfc1">

**Comment by smomin** [comment]
I am closing this issue since I have not heard back.  Please reopen if problem persists.

**Comment by vivekraj** [comment]
The issue still persist on 1.1.3. Also tried adding two extensions, one for the parent and one for the sub collection. (As explained on https://github.com/algolia/firestore-algolia-search/issues/56#issuecomment-905926093) Tried pointing to the same index and different indexes as well. But it still fails the sync.

**Comment by vivekraj** [comment]
> The issue still persist on 1.1.3. Also tried adding two extensions, one for the parent and one for the sub collection. (As explained on [#56 (comment)](https://github.com/algolia/firestore-algolia-search/issues/56#issuecomment-905926093)) Tried pointing to the same index and different indexes as well. But it still fails the sync.

Figured it out. The API key didn't had access to the sub collection's aloglia index
