### ISSUE TITLE
select firestore database

### ISSUE THREAD

**Issue by aronsuarez** [algolia/firestore-algolia-search#178]
Multiple firestore databases in one project is now in preview, it would be very nice to have the option to specify the trigger database

**Comment by smomin** [comment]
Can you provide more details and screenshots for this request?

**Comment by aronsuarez** [comment]
Checkout this blog post: https://cloud.google.com/blog/products/databases/manage-multiple-firestore-databases-in-a-project

This is a value that will set when the firestore instance is created 

`getFirestore(app, 'some-db-name')`

**Comment by smomin** [comment]
@aronsuarez 

The provisioning of the function to monitor changes to a database is managed by the firebase team.  They would need to enable the ability to set up one extension to monitor multiple database.  Right now, you can install the extension multiple times to monitor one database per extension.  Have you tried this approach?

**Comment by aronsuarez** [comment]
@smomin 

I know the problem with observing multiple databases, but this isn't what I mean. I speak of installing the extension multiple times, but how can I configure the trigger database?

**Comment by smomin** [comment]
@aronsuarez 

I have posted a question to the Firebase team if the extension is allows to select a trigger.  If there is a path forward, I will get it implemented.

**Comment by smomin** [comment]
hey @aronsuarez i have created a RC version of the extension.  

https://console.firebase.google.com/project/_/extensions/install?ref=algolia/firestore-algolia-search@1.1.4-rc.0

Try it out.

**Comment by smomin** [comment]
Pushing this feature in v1.1.4.

**Comment by ozayr** [comment]
The extension is currently not using the specified firestore database even after giving the correct database id its still only indexing data from (default)
