### ISSUE TITLE
Updated to mac Sonoma: issue with functions watching wrong directory

### ISSUE THREAD

**Issue by dubitoergo** [algolia/firestore-algolia-search#180]
After upgrading to Sonoma, when the algolia extension is enabled and I run the emulators locally, they override my functions watch directory with the cached extensions directory

```
functions: Watching "/Users/me/.cache/firebase/extensions/algolia/firestore-algolia-search@1.1.3/functions" for Cloud Functions...```

**Comment by smomin** [comment]
The extension project structure is provided by the Firebase team.  Maybe open a ticket with the Firebase team.

**Comment by benomatis** [comment]
@dubitoergo I have just hit this error today in the firebase emulator, and in my case it was a problem with a misconfigured index file in the firebase/functions folder that exports all my functions, it had a line referring to a function that I deleted earlier, removing that line allowed the emulator to rebuild itself correctly without the error.

**Comment by smomin** [comment]
Thank you for providing your resolution.
