### ISSUE TITLE
Firestore "Extension" and >1 Collection 

### ISSUE THREAD

**Issue by jimb2834** [algolia/firestore-algolia-search#184]
Hello,

Usecase: We assumed using Algolia with Firestore allowed us the ability to add many collections from one project. 

Is there a limitation of ONE collection per Firestore project?

In setting up the extension (version 1.1.3) it states 

a) Collection Path 
b) Algolia Index Name 

Because it is only 1 extension per Firestore project it would be assumed the extension is used across all "collections" and you would add
inscope Collection names inside Algolia. Then, within Algolia you would add indexs.

Where do we add other collections from the same project?

**Comment by smomin** [comment]
The Firebase Extension framework allows for one extension per collection.  This is not an Algolia limitation but a Firebase Extension Architecture.  If you are looking to monitor multiple collections and send it to the Algolia, you can install the Algolia Firestore collection multiple times.

**Comment by jimb2834** [comment]
@smomin - Yes I did try and it works. If they add that to the documentation it would be helpful. Thank you for the reply

**Comment by smomin** [comment]
I will add this my to do list.
