### ISSUE TITLE
Add correct guide example while doing configuration (Feature Request).

### ISSUE THREAD

**Issue by bleedweedsuz** [algolia/firestore-algolia-search#187]
In the configuration section, when adding a subcollection, use a specific path format similar to what is illustrated in the README.md document. For example, instead of writing path/to/collection, use path/{id}/collection. This example clearly demonstrates the use of a dynamic segment ({id}) within the path, ensuring a more practical and consistent guide for users across both the documentation and the configuration instructions.

Current example image:
![Screenshot 2023-12-01 at 4 50 46 PM](https://github.com/algolia/firestore-algolia-search/assets/10117919/b97486d7-0c91-4fe4-ba6d-834e4629d7a7)

my purpose example)\:
![Screenshot 2023-12-01 at 4 59 22 PM](https://github.com/algolia/firestore-algolia-search/assets/10117919/e4342f37-3ac0-4329-9aa8-5533220b0235)

need to change: [extension.yaml](https://github.com/algolia/firestore-algolia-search/blob/cd9d7ff15347f6af026e164f1db90210b676e661/extension.yaml#L96C118-L96C136)

**Comment by smomin** [comment]
the configuration is now updated.
