### ISSUE TITLE
What's the right authentication setup for a transform Cloud Function endpoint?

### ISSUE THREAD

**Issue by derFunk** [algolia/firestore-algolia-search#194]
Hi there,

maybe I'm missing something, but currently it seems that the transform Cloud Function endpoint is called by Algolia without any authentication: See [transform.js](https://github.com/algolia/firestore-algolia-search/blob/a62ccdaa6251a0cfffdfa40d3cd782b450f9e752/functions/src/transform.ts).

I tried giving ext-firestore-algolia-search@{project}.iam.gserviceaccount.com `Cloud Functions Invoker` permissions, but that did not help.

The result was a 403 with `reason: Unexpected token < in JSON at position 0 at ...` as in https://github.com/algolia/firestore-algolia-search/issues/132, due to Firebase returning HTML for the error message `ERROR 403 (FORBIDDEN): Your client does not have permission to get URL /transform-function-name`.

Only giving `Cloud Functions Invoker` role to the `allUsers` principal on my transform cloud function worked eventually, but that's pretty insecure since the endpoint is now public.

Any pointers?

**Comment by smomin** [comment]
The Transform Firebase Function should be set up to unauthenticated users.

**Comment by smomin** [comment]
Closing this issue since the question has been answered.
