### ISSUE TITLE
Extension is failing to fully index collection 

### ISSUE THREAD

**Issue by JohnValanidas** [algolia/firestore-algolia-search#208]
We have several collections using this extension and do not have any problems except for one of our collections. When the collection is set up to use the extension, it gets stuck in "processing," and we get the following error every time the task queue fires off a task, about once an hour. 

```
Unhandled error FirebaseFunctionsError: The principal (user or service account) lacks IAM permission "cloudtasks.tasks.create" for the resource "projects/REDACTED-PROJECT/locations/us-central1/queues/ext-firestore-algolia-search-indexed-REDACTED-COLLECTION-executeFullIndexOperation" (or the resource may not exist).
    at FunctionsApiClient.toFirebaseError (/workspace/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js:305:16)
    at FunctionsApiClient.enqueue (/workspace/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js:146:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

We've set it up via the CLI each time, and it's been done from two different accounts with full ownership of the project. I know in one of the other issue threads, it was indicated that this error could be from a permission issue with the account setting up the extension, but that is not the case here. 

Any insight would be great. I can provide any additional information as well.

**Comment by smomin** [comment]
Yes, the service account or user that installed and configured the extension doesn't have the necessary permission which is called out in the error message.  This is not something the extension has control over.  You will have to open a ticket with Google Firebase team to help with the permission issues.
