### ISSUE TITLE
ExecuteIndexOperation of delete does not work w/ altObjectId

### ISSUE THREAD

**Issue by SeokyoungYou** [algolia/firestore-algolia-search#210]
I added (path) to altObjectID in Firebase Extension.

Unfortunately, create and update operations are working well but delete operation is not working because the index is deleted by `doc.id`.

- I uploaded PR: https://github.com/algolia/firestore-algolia-search/pull/209

**Comment by smomin** [comment]
hey @SeokyoungYou 

Go ahead and test this RC which has the code changes, https://console.firebase.google.com/project/_/extensions/install?ref=algolia/firestore-algolia-search@1.2.4-rc.0)

**Comment by SeokyoungYou** [comment]
@smomin Thanks. It works well. Could I know when 1.2.4 version will be updated?

**Comment by smomin** [comment]
I am releasing the extension with this change.

**Comment by SeokyoungYou** [comment]
@smomin I am only visible version 1.2.2 in Firebase console. How could I access v1.2.4?

**Comment by smomin** [comment]
It’s not released yet.  Firebase team is reviewing it.Sent from my iPhoneOn May 8, 2024, at 4:50 PM, Quartz (Seokyoung You) ***@***.***> wrote:﻿
@smomin I am only visible version 1.2.2 in Firebase console. How could I access v1.2.4?

**Comment by SeokyoungYou** [comment]
Thanks!
