### ISSUE TITLE
How do you exclude documents that contain a specific attribute?

### ISSUE THREAD

**Issue by ItsAnoch** [algolia/firestore-algolia-search#219]
Is there a way to configure the extension only to include documents where 'isAvailableForPurchase' is true, and ensure that documents are removed from the index if this value changes to false?

**Comment by smomin** [comment]
At this time, its not available configure this to include or exclude.  For now, you can use Algolia Rules to add a filter to only return documents with 'isAvailableForPurchase' is true.

**Comment by ItsAnoch** [comment]
> At this time, its not available configure this to include or exclude. For now, you can use Algolia Rules to add a filter to only return documents with 'isAvailableForPurchase' is true.

ok, thanks
