### ISSUE TITLE
Firebase Extension: not able to upgrade Search Firestore with Algolia to new version

### ISSUE THREAD

**Issue by Snow31ind** [algolia/firestore-algolia-search#224]
I'm not able to upgrade the extension from version `1.2.4` to `1.2.7`. The version upgrade API call triggered a CORs error.

Is there anything I can do to fix this?

![image](https://github.com/user-attachments/assets/46b05341-790f-45fb-8b29-dae0f531f825)
![image](https://github.com/user-attachments/assets/57af4abc-e342-4e59-a4eb-e496d17aad27)

**Comment by smomin** [comment]
hey @Snow31ind, you might need to open this with the Firebase team since I don't control the upgrade process.
