### ISSUE TITLE
ALGOLIA - Taking to long to process

### ISSUE THREAD

**Issue by prachipal19** [algolia/firestore-algolia-search#230]
I installed the Algolia extension.
I configured it with the necessary settings.
The extension is currently in the processing status, but it is taking too long.

Expected result
The extension should process quickly and complete the configuration.
Actual result
The extension is stuck in the processing status for an extended period.

**Comment by CodeRebirth** [comment]
Same with me

**Comment by prachipal19** [comment]
I followed these steps, and the issue was resolved:

For the Algolia API Key, go to the Algolia dashboard and navigate to Settings > API Keys > All API Keys, then click New API Key. Under Indices, select the index you created earlier. In the ACL field, include these options: addObject, deleteObject, listIndexes, deleteIndex, editSettings, and settings. Click Create, then copy the generated API Key and enter it in the appropriate field.

**Comment by CodeRebirth** [comment]
Yes, this fixed my problem too. Thanks
