### ISSUE TITLE
executeFullIndexOperation failed

### ISSUE THREAD

**Issue by gspsteve** [algolia/firestore-algolia-search#231]
Installing a new Algolia Firestore Extension results in error
`Function execution took 1310 ms, finished with status code: 500`

```
ext-firestore-algolia-search-posts-executeFullIndexOperationgcgprbk9sbxv Error: Unhandled error
    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)
    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)
    at /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:91:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

Previous Extension / Algolia Google Cloud Function has worked fine in the meantime i upgraded firebase-tools to version 13.24.1 so maybe it stopped working with the update

**Comment by gspsteve** [comment]
Has anyone found a solution to this issue yet? I'm still unable to use the Algolia Firestore extension to index existing documents. I'm encountering the same error:

Function execution took 1310 ms, finished with status code: 500

I initially thought the issue might be related to upgrading firebase-tools to version 13.24.1, as my previous extension setup was working fine before the update. Has anyone else experienced this or found a workaround? Any news or tips would be greatly appreciated!

**Comment by bayhax-wang** [comment]
any solution?

**Comment by gspsteve** [comment]
The Problem was not the Firestore Extension, it was a field with to many characters. I found the hint in the Algolia Monitoring...
