### ISSUE TITLE
Mutate and Create Fields When Sending to Algolia

### ISSUE THREAD

**Issue by PeterCardenas** [algolia/firestore-algolia-search#31]
Hello! We currently have some cloud functions that mutates our Algolia indices when relevant documents are created, updated, or deleted, and we are excited to discover that this Firebase extension can help remove some of this code. However, one of our indices change one field to a more search-friendly form, i.e. turning a serialized JSON of rich text into plaintext. We would like to move all of our function code to using this extension, but this is currently blocking us from doing so. Thanks!

**Comment by smomin** [comment]
hey Peter, I want to better understand your use case.  Are you looking to inject your logic to post process fields values before it is indexed into Algolia?

**Comment by PeterCardenas** [comment]
hi! thanks so much for getting back to me, that is indeed my use case.

**Comment by smomin** [comment]
I will have to do some R&D on how to call external functions.

**Comment by smomin** [comment]
hey @PeterCardenas, created a PR for the post processing.
