### ISSUE TITLE
New Documents Added When Adding Field To Preexisting Documents

### ISSUE THREAD

**Issue by PeterCardenas** [algolia/firestore-algolia-search#35]
We recently ran a script to add a field to all pre-existing documents, and even though this field was not part of the indexable fields list, documents that were previously not in the index were added to it. We would like only for documents to be added to the index if they have all the indexable fields, and only if the indexable fields have changed.

**Comment by smomin** [comment]
Hey Peter, I will look into this later this week.

**Comment by PeterCardenas** [comment]
Thank you so much Sajid!
