### ISSUE TITLE
Subcollections support

### ISSUE THREAD

**Issue by zphoenixz** [algolia/firestore-algolia-search#36]
It's not possible to have a subcollection tied to the function, it has to be on the root or it won't work.

**Comment by smomin** [comment]
I am not sure I understand your use case.  If you can provide more details, I can try to look into it.  thanks

**Comment by zphoenixz** [comment]
Sorry, what I meant is that if it's possible to use listeners to collections with interpolated document keys something like "parent_collection/$document_id/target_collection"

**Comment by smomin** [comment]
It is supported.  Example syntax is `parent_collection/{parentId}/target_collection`.  One note, there is not depublication process on subcollections.  So if there is a record with the same data in multiple sub collection but with different ids, you will have multiple corresponding records in Algolia.

**Comment by smomin** [comment]
Also, if you plan to use a new index for the subcollection, make sure the API key you are using has the proper permission.

**Comment by smomin** [comment]
Reopen the issue if you have further questions.

**Comment by icybergenome** [comment]
Hi @smomin !
Is it possible for generic path as well something like `parent_collection/*/target_collection`, because I tried it already and it didn;t work. Or it is only possible for specific `parentId`.

**Comment by BenWueb** [comment]
Could you provide the proper syntax for adding a subcollection. I have tried the below with no success.

Recipes/{parentId}/recipes
Recipes/{documentId}/recipes

**Comment by smomin** [comment]
Can you provide more detail on this issue?  Are the parent and child collection both are called recipes?

**Comment by guplem** [comment]
@smomin I have the following structure:
 - ParentCollection
    - Document1
        - CollectionA
    - Document2
        - CollectionB
    - Document3
        - CollectionC

How can I index the contents of all (documents and collections) inside ParentCollection? Should I just use the `/ParentCollection` path?
