### ISSUE TITLE
Filtering Tags as Firestore Arrays of Maps (Objects)

### ISSUE THREAD

**Issue by ImanYZ** [algolia/firestore-algolia-search#39]
In our Firestore collection, tags are listed as Arrays of Maps (objects), like the following document:
```
{...,
tags: [
TagId: "uYgvhNdciHcuK7ioGZEv",
Title: "SARS-CoV-2 (COVID-19)"
]}
```
How can I filter the searh results using these tags?

**Comment by smomin** [comment]
Hello @ImanYZ, is this a question on indexing or how to configure Algolia?  If its the latter, you can open a support ticket or look at the great documentation that is provided.   Here is a quick search I did on search filter, https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/filters-and-facetfilters/.
