### ISSUE TITLE
Error when inserting data from Client

### ISSUE THREAD

**Issue by superdiazzz** [algolia/firestore-algolia-search#51]
Hi, am really new using algolia, i don't know but i have following all step in firebase extension doc. I install algolia through firebase extension.

I created new api key and divert it to proper indices(by creating new indices). But i got error in algolia functions when i inserted new record from my website, what logs said is:

> Error when performing Algolia index {"transporterStackTrace":[{"triesLeft":3,"response":{"isTimedOut":false,"status":403,"content":"{\"message\":\"Index not allowed with this API key\",\"status\":403}"},"host":{"accept":2,"url":"NZ3GVUOMSD.algolia.net","protocol":"https"},"request":{"url":"https://NZ3GVUOMSD.algolia.net/1/indexes/algoId/batch?x-algolia-agent=Algolia%20for%20JavaScript%20(4.8.6)%3B%20Node.js%20(10.24.1)%3B%20firestore_integration%20(0.5.1)","connectTimeout":2,"data":"{\"requests\":[{\"action\":\"partialUpdateObject\",\"body\":{\"objectID\":\"crSuskBJaQpfOAODUNey\",\"title\":\"Test 5\",\"category\":\"kesehatan\",\"lastmodified\":{\"_operation\":\"IncrementSet\",\"value\":1626963102502}}}]}","method":"POST","headers":{"x-algolia-application-id":"NZ3GVUOMSD","x-algolia-api-key":"*****","content-type":"application/x-www-form-urlencoded"},"responseTimeout":30}}],"name":"ApiError","status":403}

Then, i checked algolia dashboard and there is nothing there, still empty. Can somebody explain to me what happened here? Thanks

**Comment by smomin** [comment]
Its seems like the API key you are using might not have the correct permissions or set to a specific index.  Can you provide me your Algolia Firebase Extension configuration and the screenshot of your API key permissions.  Make sure to redact important information.

**Comment by superdiazzz** [comment]
> Its seems like the API key you are using might not have the correct permissions or set to a specific index. Can you provide me your Algolia Firebase Extension configuration and the screenshot of your API key permissions. Make sure to redact important information.

Sure, this is my config
![Screen Shot 2021-07-23 at 06 44 53](https://user-images.githubusercontent.com/10770867/126722590-8c9fd3ae-03fd-4a3b-962b-a86b163524a0.png)
and my api key ini red box
![Screen Shot 2021-07-23 at 06 47 03](https://user-images.githubusercontent.com/10770867/126722624-b6f0cf1f-41ca-4c5f-a2b3-6a6ea73f3717.png)

**Comment by superdiazzz** [comment]
@smomin can you help me, sir?

**Comment by smomin** [comment]
Yes, the index name you are using in the firestore extension does not match the name that is permissioned in algolia.  In you firestore extension configuration, change the name to dev_skillBrau.  That should fix it.

**Comment by superdiazzz** [comment]
> Yes, the index name you are using in the firestore extension does not match the name that is permissioned in algolia. In you firestore extension configuration, change the name to dev_skillBrau. That should fix it.

thank you, it's works
