### ISSUE TITLE
Multiple Collection Support

### ISSUE THREAD

**Issue by kevin-induro** [algolia/firestore-algolia-search#55]
We currently sync multiple collections into different indices in Algolia. From reviewing the implementation here, it does not seem like that's currently supported. The Algolia website (https://www.algolia.com/developers/firebase-search-extension) does list that it's possible ("Set up or combine multiple collections, or sub-collections, into a single search index"), so am I missing something?

**Comment by smomin** [comment]
The statement is referring to setting up your extension on multiple collection pointing to the same index.  With this approach you will have a mix of content in one index.

**Comment by kevin-induro** [comment]
I could figure something out while pointing to a single index, but no, I'd prefer if I could have each collection pointing to a different index.

**Comment by smomin** [comment]
If you want each collection to point to a separate Algolia index, this is possible.  Install the extension on each collection and in the configuration set the Algolia index for that collection.

**Comment by kevin-induro** [comment]
I never realized you could install multiple instances of an extension. Thanks!
