### ISSUE TITLE
[Feature Request] Sync with collections OR collectionGroups

### ISSUE THREAD

**Issue by deimantasa** [algolia/firestore-algolia-search#56]
Hello devs,

First of all - thank you for such an amazing and time saving tool. It really helps us to move much faster with Fire + Algolia.

One thing I found missing is support for [collectionGroups](https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html). It would extremely help as currently, we've to have `global` `collection` in order for it to sync with Algolia. However there are many instances as it's better to nest it under some `collection` instead of keeping everything `global`.

As a workaround, we have subcollection and collection of the same thing. Collection is used for algolia only, and subcollection for other things. It would be great to rely on only `subcollection` in this case as it would take away this constant sync between main `subcollection` and `collection` which is only used in `Algolia`.

Looking forward!

Cheers

**Comment by dvarnes** [comment]
Do you know that the existing function already works for sub-collections?

Just specify the full sub-collection path:   `rootCollection/{someDocId}/subCollection{someDocId}`

**Comment by deimantasa** [comment]
This will index only specific collection. My goal is to index `all collections` with the same name (`collectionGroup`).

Example:
`collection` - `users`
`subCollection` - `cars`

I want to listen for changes that happen in `any subcollection of cars` (thus `collectionGroup`) instead of single one as per your sample.

**Comment by deimantasa** [comment]
Wow - that's terrific. Just ran a test and indeed - it works!

Would be nice to add some description about it, as it was not clear in the beginning that `sub-collections` are taken into account as well.


Thank you for prompt help!

**Comment by vivekraj** [comment]
@smomin 

> You will need to have two Algolia extensions installed. One to listen on the users collection and the other to listen for the users/{parentId}/cars subcollection.

Both points to the same algolia index or should be pointing to separate indexes?
