### ISSUE TITLE
Can't run firestore-algolia-search in bash script

### ISSUE THREAD

**Issue by Lucas-L** [algolia/firestore-algolia-search#64]
Hello everyone,

I've been trying to run the restore script for `firestore-algolia-search`. According to other issues, decided to run it from a bash script: 

```
#!/bin/bash

LOCATION=us-central1\
PROJECT_ID=project-id\
ALGOLIA_APP_ID=111111\
ALGOLIA_API_KEY=111111\
ALGOLIA_INDEX_NAME=index\
COLLECTION_PATH=path\
FIELDS=fields\
GOOGLE_APPLICATION_CREDENTIALS=./key.json\
npx firestore-algolia-search
```

But then the output is `firestore-algolia-search: command not found `. I'm writing this issue here because other npx script would work in bash scripts. npx is installed globally and the command is working outside of bash (but no with parameters  declared beforehand)

Thanks a lot

**Comment by cvanputt** [comment]
What was the solution for this? I am having this issue
