### ISSUE TITLE
Every Query performed on Algolia counts up towards the read usage count of Cloud Firestore

### ISSUE THREAD

**Issue by nicolopadovan** [algolia/firestore-algolia-search#68]
As far as I understand, the extensions should only bridge new data to Algolia, which stores the received data in records and sends those back to the user whenever a query is performed.
However, I have noticed that whenever I perform a query on my client (iOS in this case) the read usage of my Cloud Firestore increases by 1 for every hit of the query (which results in an enormous quantity of reads).
Is this an intentional behavior? 
Thanks.

**Comment by Haroenv** [comment]
do you mean an algolia query or firebase query? how are you searching?

**Comment by nicolopadovan** [comment]
I mean algolia query, and I’m using the Instasearch module for iOS.

Il giorno lun 27 set 2021 alle 17:51 Haroen Viaene ***@***.***>
ha scritto:

**Comment by nicolopadovan** [comment]
> do you mean an algolia query or firebase query? how are you searching?

I mean Algolia query, and I’m currently using Instasearch to perform queries.

**Comment by Haroenv** [comment]
there's no logic to do a firebase query on every search query, is it possible you are doing that code manually in your frontend?

**Comment by nicolopadovan** [comment]
> there's no logic to do a firebase query on every search query, is it possible you are doing that code manually in your frontend?

In fact, I thought so: but by removing the extension, the usage stops increasing, while I can still query through the already present records. As soon as I link the extension again, however, the usage starts increasing again.
I am using infinite scrolling, if this info can be helpful at all.

**Comment by Haroenv** [comment]
Sorry, I'm not sure how the two can be related. Do you maybe mean that every time you make a change in the firebase data it will incur a read of that data, as it needs to be updated in algolia?

**Comment by nicolopadovan** [comment]
> Sorry, I'm not sure how the two can be related. Do you maybe mean that every time you make a change in the firebase data it will incur a read of that data, as it needs to be updated in algolia?

No, I am not editing the Firestore database at all while querying. 
Also, I noticed that even after I removed the extension the problem persists, but I am absolutely sure that I am not reading the data from my client (there isn't any code at all that reads the database in my whole app).
Whenever I query data from Algolia, the FIrestore usage increases, and it's not related to my client or to my own functions (there isn't any).

**Comment by Haroenv** [comment]
search doesn't pass through firebase, so I don't know what can explain this. Do you have the code somewhere that it can be tried out (you can erase the credentials)

**Comment by nicolopadovan** [comment]
> search doesn't pass through firebase, so I don't know what can explain this. Do you have the code somewhere that it can be tried out (you can erase the credentials)

Here it is: https://github.com/nicolopadovan/PublicRepo/tree/dev

I moved all the algolia-related data to this project, which doesn't even import Firebase at all, and I tried using it with my API key etc, and the Firestore usage still increased.

To use it, just download it and then run `pod install` in its directory from the terminal.

**Comment by Haroenv** [comment]
cc @VladislavFitz it's iOS

**Comment by smomin** [comment]
hello @nicolopadovan, are you still encountering the extra reads on your firestore db?

**Comment by nicolopadovan** [comment]
> hello @nicolopadovan, are you still encountering the extra reads on your firestore db?

Hello @smomin 
Finally, after basically rebooting everything (intended as deleting and re-creating the projects both on Algolia and Firebase and then bridging them together), I am not getting extra reads anymore. I don't know what could have caused the issue, but luckily it appears to be gone.
