### ISSUE TITLE
Firestore DocumentReference path in Algolia Object

### ISSUE THREAD

**Issue by iansmathew** [algolia/firestore-algolia-search#72]
It would be wonderful to have a configuration option in the extension setup to allow passing the document reference path of the firestore document to the transform functions and algolia index. Perhaps as a key called `firestore_path`

This would allow users to use Algolia to search for documents across collections and then return the actual Firestore document on the front end.

Currently the only linking between Firestore Documents and Algolia Objects are the object ID (AKA Doc ID). This isn't enough on its own to link back to the original document. A full path of the document would allow for this to happen.

**Comment by luigi-agosti** [comment]
Good idea, this could be useful... maybe more generically could be to pass reference in the transform and let users of the extension decide what to do.
Thanks
