### ISSUE TITLE
extension error

### ISSUE THREAD

**Issue by leblancmeneses** [algolia/firestore-algolia-search#82]
We upgraded to:

Search with Algolia
algolia/firestore-algolia-search@0.5.9

We are seeing this error:

ext-firestore-algolia-search-executeIndexOperation
Error when performing Algolia index { FetchError: invalid json response body at https://accounts.google.com/ServiceLogin?service=ah&passive=true&continue=https://uc.appengine.google.com/_ah/conflogin%3Fcontinue%3Dhttps://xxxxxx/extAlgoliaSearchCustomers reason: Unexpected token < in JSON at position 1 at /workspace/node_modules/node-fetch/lib/index.js:272:32 at process._tickCallback (internal/process/next_tick.js:68:7) message: 'invalid json response body at https://accounts.google.com/ServiceLogin?service=ah&passive=true&continue=https://uc.appengine.google.com/_ah/conflogin%3Fcontinue%3Dhttps://xxxxxxx/extAlgoliaSearchCustomers reason: Unexpected token < in JSON at position 1', type: 'invalid-json' }

**Comment by smomin** [comment]
Hello @leblancmeneses,

We have tested this on our Firebase Database and we did not find any issues.  Can you provide more details?  Also, based on errors, it seems like Service User issue.  You might want to also open a ticket with Firebase team.  Thanks.

Sajid

**Comment by smomin** [comment]
Closing the ticket due to no response.
