### ISSUE TITLE
Invalid secret id

### ISSUE THREAD

**Issue by kjetilhp** [algolia/firestore-algolia-search#84]
Error: HTTP Error: 400, Secret ID `***my-api-key***` is invalid, must be of form `projects/*/secrets/*/versions/*`

Created the key as recomended, and have previously installed working extension for a collection with this key, now trying to add another for another collection, I get this error.

**Comment by Haroenv** [comment]
Have you tried the steps described in https://github.com/algolia/firestore-algolia-search/pull/81#issuecomment-973936681? 

cc @i14h

**Comment by kjetilhp** [comment]
@Haroenv I have not, I'm doing this commandline with vars file. But I'll give it a try in the web gui.

**Comment by kjetilhp** [comment]
@Haroenv works in ui, so I guess this isn't algolia related.

**Comment by agreaves** [comment]
Any fix for this from the command line / or ideally without requiring API access for the Secrets API. We need to be able to install the Algolia extension automatically and do not have access to the GUI, so the recent change now breaks that process.

Alternatively, is there a straightforward way to enable the Secrets API from the command line.

**Comment by benomatis** [comment]
@Haroenv The command line installation appears to require the secret path from the Secrets Manager, and not the Algolia secret itself. The UI installation generates the secret in the Secrets Manager automatically, and I'm not sure if you can manually create that secret (its naming and all looks quite specific). So wondering if this is actually a bug in the command line script, but if anything, it could definitely be documented better on the README which refers to the Algolia API Key and has no mention of the Secrets Manager or the required format (the secret path)...
