### ISSUE TITLE
Algolia API Key Description

### ISSUE THREAD

**Issue by jelizarovas** [algolia/firestore-algolia-search#85]
In the API key description, for first time users who just want to set up as quickly as possible, when I was asked for API key, I have two options in algolia api keys - Search-Only API key or Admin API key. In the description it says Do not use the admin API key, so naturally revert to the other available API key which is Search Only. Since it says "We recommend creating new key", - I assume it's best practice, but to play around my "Search-Only" key should work just fine. Wrong. I set up the index, and cannot get records no matter what i do. Until i go to "Search API Logs" and see all of my POST requests in the 400 code. So now i see that if i do not create a new api key it will never work.

Suggestion change the wording to the likes of:

Algolia API Key Description
We require API key with “addObject”, “deleteObject”, “listIndexes”, “deleteIndex”, “editSettings”, and “settings” permissions. Do not use the Admin API key or Search Only API Key.

![image](https://user-images.githubusercontent.com/15138718/144060520-8a1ea29a-f248-4a52-b699-fe54606033b8.png)

![image](https://user-images.githubusercontent.com/15138718/144061975-1bebbd59-becf-4aa1-9e8c-e1fbb974ed03.png)

![image](https://user-images.githubusercontent.com/15138718/144062012-02fb4a40-afa0-47bf-aa1d-ff27db22a2e2.png)

**Comment by Haroenv** [comment]
Not fully sure whether that explicitly needs to be said, as just before it mentions to have addObject etc. as permissions.

The description is declared here

https://github.com/algolia/firestore-algolia-search/blob/e9e75ca21bad782e1f4d601dfb4a559aeccf5182/extension.yaml#L112

**Comment by smomin** [comment]
I don't think we need to explicit say this considering we are putting all the rights needed on the permission.
