### ISSUE TITLE
Algolia API Key: creation failure

### ISSUE THREAD

**Issue by maxmarchionda** [algolia/firestore-algolia-search#86]
I would like to use this extension, however my organization at work has put in restrictions around where secrets can be created in the Google Secret Manager so simply creating a secret using this extension fails:
```
Error: HTTP Error: 400, Constraint constraints/gcp.resourceLocations violated for [redacted] attempting to create a secret in [global]. For more information, see https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations.
```
A solution to this problem would be to allow myself to create the secret ahead of time and skip this step. Interested in hearing your thoughts.

**Comment by smomin** [comment]
Hey Max,

It may look like this would be a conversation with the Firebase team who is managing the Extension installation and configuration flow.  I would recommend talking to them first.

**Comment by joehan** [comment]
Hey @maxmarchionda  - Joe from the Firebase Extension team here. Thanks for the suggestion, we will definitely consider adding support for this to our console install flow. 

Fortunately, you can do this today! You can use existing secret if you deploy the extension via `firebase deploy`. Docs for the feature can be found here: https://firebase.google.com/docs/extensions/reuse-project-config - for your specific case, I recommend doing the following:

- If you don't have it yet, install the firebase-tools CLI on your machine (`npm install firebase-tools -g`)
- If you don't have a firebase directory yet, set one up in a clean directory with `firebase init`
- Run `firebase ext:export`. This will add any extensions currently installed on your project to your `firebase.json` & `extensions/` directory
- In the `extensions` section of` firebase.json`, add a new entry for an instance of the Algolia search extension, like so: 
```
"extensions": { "my-algolia-instance": "algolia/firestore-algolia-search@0.5.6" }
```
- In the extensions directory, add a file named `{instance-id}.env` (in the example above, this will be `my-algolia-instance.env`, containing the configuration for the extension. You can reference an already existing secret here.
- Finally, run `firebase deploy --only extensions` to deploy extensions to your project

**Comment by smomin** [comment]
hey @maxmarchionda, is the issue resolved?
