### ISSUE TITLE
Missing module in script to import existing documents

### ISSUE THREAD

**Issue by cpena** [algolia/firestore-algolia-search#87]
Hi,

I 'm trying to import existing Firestore documents using `npx firestore-algolia-search` and following [this guide](https://github.com/algolia/firestore-algolia-search/blob/main/POSTINSTALL.md) , but I'm receiving this error:
```
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
Cannot find module '@google-cloud/firestore'
```

NODE v10.23.3
NPM v6.14.11

**Comment by smomin** [comment]
Please provide the full cli command that was executed.  Make sure to redact sensitive data.

**Comment by cpena** [comment]
Hi , this is the full command:
```
LOCATION=us-east1 \
PROJECT_ID=my_project \
ALGOLIA_APP_ID=xxxxxxxx \
ALGOLIA_API_KEY=xxxxxxx \
ALGOLIA_INDEX_NAME=project \
COLLECTION_PATH=Project \
FIELDS=field1,field2 \
GOOGLE_APPLICATION_CREDENTIALS=credential.json \
npx firestore-algolia-search
```

**Comment by smomin** [comment]
I am not sure if this might be you local environment.  Can you execute this command in a Node docker container?

**Comment by smomin** [comment]
hey @cpena, were you able to execute this commend in a Node docker container?  Did it resolve your issue?
