### ISSUE TITLE
Configuring, when to store a document

### ISSUE THREAD

**Issue by bennihz** [algolia/firestore-algolia-search#91]
I could not find such a feature in the docs. Can I configure the function to only create an index in Algolia, if for example a 'verified' property is 'true'?

**Comment by Haroenv** [comment]
With the current implementation it's not possible to sync only part of the records, but you can use filters to choose not to display all records using Algolia

**Comment by iansmathew** [comment]
@bennihz I believe you can just set a transform function that exits the function without returning anything (as opposed to returning the data payload) and that would result in the object not being indexed

**Comment by smomin** [comment]
If I understand this issue, this might be related to issue #57.  Take a look and see if this helps.
