### ISSUE TITLE
Skip certain documents from being indexed

### ISSUE THREAD

**Issue by garyodonoghue** [algolia/firestore-algolia-search#98]
Is there a way to skip/ignore particular document updates, i.e. filtering. For example if i have a collection of documents, each document containing a 'type' property, and I'm only interested in document updates where type == 'sport', how could i achieve this? 

I thought of using the transform function to check the 'type' and return an empty response if it's not a value im concerned with, e.g. 'sport' in this example, but looking at the code [here](https://github.com/algolia/firestore-algolia-search/blob/38b5933c692196befdce159911d360a70e6af21c/functions/src/extract.ts#L61), I'm not sure that would be the correct approach. 

Any suggestions appreciated, thanks

**Comment by smomin** [comment]
Hey @garyodonoghue 

At this time, there is no way to skip documents, but I will consider this feature.  The only approach is to set up filters during query time to filter out results based on attribute.  You can look at this issue if this helps, #57.

**Comment by smomin** [comment]
Closing this issue for now.

**Comment by omarsourour** [comment]
@smomin Doesn't this PR #58 handle this issue? It seems to me from there that if I add a transform function that returns a null value, the index of the document will not be created.

**Comment by i14h** [comment]
Yes I think @smomin when you wrote the transform function you allowed a way to skip the entry being indexed, no?

**Comment by smomin** [comment]
Hey Omar, this PR was not merged.  You can use the Algolia rules to filter out record based on a record property.

**Comment by smomin** [comment]
No, I initially was going to merge this but then back away from doing it.  I will take a look at it again.
