### ISSUE TITLE
Update from X.X.X to 0.5.9 Breaks Connection to Algolia

### ISSUE THREAD

**Issue by gottliebtj** [algolia/firestore-algolia-search#99]
Repeatable Steps:

1. Install firebase extension 0.5.4
2. Connect Algolia via custom API keys 
3. Import collections via firestore-algolia-search npx package.
4. change firestore entries and succussfully see them update in algolia.
5. update firebase extension to 0.5.9.
6. Try and change firestore data and see reflection but nothing changes unless i manually run the migrations via the cli.

Thanks in advance please help!!!!!!!

**Comment by smomin** [comment]
Please check the extension logs for errors.
<img width="1000" alt="Screen Shot 2022-03-18 at 12 12 37 PM" src="https://user-images.githubusercontent.com/1305323/159069350-b2ee6eb2-3473-4fb2-882e-072280a24f52.png">

**Comment by clintgc** [comment]
`Error when performing Algolia index {"transporterStackTrace":[{"triesLeft":3,"host":{"protocol":"https","url":"HLG1XKKK7M.algolia.net","accept":2},"response":{"content":"{\"message\":\"Index not allowed with this API key\",\"status\":403}","status":403,"isTimedOut":false},"request":{"responseTimeout":30,"method":"POST","data":"{\"requests\":[{\"action\":\"partialUpdateObject\",\"body\":{\"Season\":{\"2021-2022\":\" BR2jzZrrv6seXmpApDrU\"},\"birth_date\":\"2008-03-09 00:00:00.000\",\"created_time\":1646839694752,\"email\":\"test91@test.com\",\"first_name\":\"Robin\",\"home_town\":\"Naperville\",\"last_name\":\"Kuzma\",\"photo_url\":\"https://firebasestorage.googleapis.com/v0/b/clutch-f0902.appspot.com/o/users%2F1MN5jeu3Y5acCvSX9g3cyjEKyQE2%2Fuploads%2F1646839702240000.jpeg?alt=media&token=751e3ac0-97e6-4156-be5d-bf8c46a99aaf\",\"player_height\":87,\"player_nationality\":\"United States\",\"player_position\":\"Center\",\"player_weight\":135,\"shot_hand\":\"Left\",\"sport\":\"Ice Hockey\",\"state_province\":\"IL\",\"team_birthyear\":\"2008\",\"team_name\":\"Chicago Mission\",\"uid\":\"1MN5jeu3Y5acCvSX9g3cyjEKyQE2\",\"objectID\":\"1MN5jeu3Y5acCvSX9g3cyjEKyQE2\",\"path\":\"users/1MN5jeu3Y5acCvSX9g3cyjEKyQE2\",\"lastmodified\":{\"_operation\":\"IncrementSet\",\"value\":1647541251244}}}]}","url":"https://HLG1XKKK7M.algolia.net/1/indexes/users/batch?x-algolia-agent=Algolia%20for%20JavaScript%20(4.8.6)%3B%20Node.js%20(10.24.1)%3B%20firestore_integration%20(0.5.9)","connectTimeout":2,"headers":{"x-algolia-api-key":"*****","x-algolia-application-id":"HLG1XKKK7M","content-type":"application/x-www-form-urlencoded"}}}],"status":403,"name":"ApiError"}`

**Comment by smomin** [comment]
@clintgc is the issue resolved?

**Comment by smomin** [comment]
Closing this issue for now.
